spring.application.name=backend

# -------DATABASE-------
spring.datasource.url=jdbc:postgresql://localhost:5432/gotogether_db
spring.datasource.username=myUsername
spring.datasource.password=myPassword

# update = creates/alters tables to match entities, never deletes data
spring.jpa.hibernate.ddl-auto=update
# create = drops and recreates tables on startup (use temporarily to fix schema issues)
# spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true

# inject sample data
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true