name: Sync to GitLab

on:
  push:
    branches: [main, master, "ci/**"] # Trigger on pushes to these branches

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetches all history for all branches and tags

      - name: Push to GitLab Mirror
        env:
          GITLAB_PAT: ${{ secrets.GITLAB_PAT }}
        run: |
          git remote add gitlab https://oauth2:${GITLAB_PAT}@git.oth-aw.de/6565/GoTogether.git
          git push gitlab --prune +refs/heads/*:refs/heads/* +refs/tags/*:refs/tags/*
